export type HealthEvidenceSource = {
  id: string;
  organization: string;
  title: string;
  scope: string;
  url: string;
  referenceYear?: number;
  jurisdiction?: "global" | "vietnam" | "united-states" | "other";
  reviewedAt: string;
  reviewDueAt?: string;
};

export const HEALTH_EVIDENCE = {
  whoChildGrowthStandards: {
    id: "who-child-growth-standards-0-5",
    organization: "World Health Organization (WHO)",
    title: "WHO Child Growth Standards",
    scope: "Chuẩn tăng trưởng 0–5 tuổi; là nguồn bắt buộc cho module tăng trưởng trẻ nhỏ, không thay bằng BMI-for-age 5–19.",
    url: "https://www.who.int/tools/child-growth-standards",
    jurisdiction: "global",
    reviewedAt: "2026-09-09",
    reviewDueAt: "2027-03-09",
  },
  whoComplementaryFeeding2023: {
    id: "who-complementary-feeding-6-23m-2023",
    organization: "World Health Organization (WHO)",
    title: "WHO Guideline for complementary feeding of infants and young children 6–23 months of age",
    scope: "Ăn bổ sung 6–23 tháng: đa dạng khẩu phần, tiếp tục bú mẹ, nguồn thực phẩm giàu dinh dưỡng, responsive feeding và an toàn thực phẩm.",
    url: "https://www.who.int/publications/i/item/9789240081864",
    referenceYear: 2023,
    jurisdiction: "global",
    reviewedAt: "2026-09-09",
    reviewDueAt: "2027-03-09",
  },
  whoImciChild: {
    id: "who-imci-child-chart-booklet",
    organization: "World Health Organization (WHO)",
    title: "Integrated Management of Childhood Illness (IMCI) Chart Booklet",
    scope: "Dấu hiệu nguy hiểm và ngưỡng thở nhanh khi ho/khó thở cho trẻ 2 tháng đến dưới 5 tuổi; chỉ dùng đúng bối cảnh sàng lọc, không tự chẩn đoán.",
    url: "https://www.who.int/docs/default-source/mca-documents/imci-chart-booklet.pdf",
    jurisdiction: "global",
    reviewedAt: "2026-09-09",
    reviewDueAt: "2027-03-09",
  },
  whoHealthyDiet2026: {
    id: "who-healthy-diet-2026",
    organization: "World Health Organization (WHO)",
    title: "Healthy diet",
    scope: "Nguyên tắc đủ, cân bằng, điều độ, đa dạng và an toàn; hành vi ăn uống hình thành từ thời thơ ấu và vị thành niên.",
    url: "https://www.who.int/news-room/fact-sheets/detail/healthy-diet",
    referenceYear: 2026,
    jurisdiction: "global",
    reviewedAt: "2026-09-09",
    reviewDueAt: "2027-03-09",
  },
  whoPhysicalActivity: {
    id: "who-physical-activity-children-adolescents",
    organization: "World Health Organization (WHO)",
    title: "Physical activity recommendations",
    scope: "Vận động cho trẻ nhỏ và nhóm 5–17 tuổi; 5–17 tuổi trung bình ít nhất 60 phút/ngày mức vừa–mạnh trong tuần, kèm hoạt động cơ/xương phù hợp.",
    url: "https://www.who.int/initiatives/behealthy/physical-activity",
    jurisdiction: "global",
    reviewedAt: "2026-09-09",
    reviewDueAt: "2027-03-09",
  },
  aasmChildSleep: {
    id: "aasm-child-sleep-duration",
    organization: "American Academy of Sleep Medicine (AASM)",
    title: "Child Sleep Duration Health Advisory",
    scope: "Thời lượng ngủ tham chiếu: 4–12 tháng 12–16h; 1–2 tuổi 11–14h; 3–5 tuổi 10–13h; 6–12 tuổi 9–12h; 13–18 tuổi 8–10h mỗi 24 giờ.",
    url: "https://aasm.org/advocacy/position-statements/child-sleep-duration-health-advisory/",
    jurisdiction: "united-states",
    reviewedAt: "2026-09-09",
    reviewDueAt: "2027-03-09",
  },
  aapdFluorideOralCare: {
    id: "aapd-fluoride-oral-care-2026",
    organization: "American Academy of Pediatric Dentistry (AAPD)",
    title: "Fluoride Therapy / Parent FAQ",
    scope: "Kem fluoride hai lần/ngày; dưới 3 tuổi smear/hạt gạo, 3–6 tuổi lượng hạt đậu; khám nha khoa đầu tiên chậm nhất quanh sinh nhật 1 tuổi.",
    url: "https://www.aapd.org/resources/parent/faq/",
    referenceYear: 2026,
    jurisdiction: "united-states",
    reviewedAt: "2026-09-09",
    reviewDueAt: "2027-03-09",
  },
  cdcDevelopmentalMilestones: {
    id: "cdc-developmental-milestones-2026",
    organization: "US Centers for Disease Control and Prevention (CDC)",
    title: "Developmental Milestones",
    scope: "Mốc phát triển thực hành 9, 12, 18, 24, 36, 48 và 60 tháng; dùng để quan sát và trao đổi, không dùng như bài test chẩn đoán.",
    url: "https://www.cdc.gov/act-early/milestones/index.html",
    referenceYear: 2026,
    jurisdiction: "united-states",
    reviewedAt: "2026-09-09",
    reviewDueAt: "2027-03-09",
  },
  cdcChokingPrevention: {
    id: "cdc-choking-hazards-2026",
    organization: "US Centers for Disease Control and Prevention (CDC)",
    title: "Choking Hazards",
    scope: "Chuẩn bị thức ăn và giám sát trẻ nhỏ khi ăn để giảm nguy cơ hóc; danh sách ví dụ thực phẩm hình tròn/cứng/dai nguy cơ cao.",
    url: "https://www.cdc.gov/infant-toddler-nutrition/foods-and-drinks/choking-hazards.html",
    referenceYear: 2026,
    jurisdiction: "united-states",
    reviewedAt: "2026-09-09",
    reviewDueAt: "2027-03-09",
  },
  whoGrowthReference: {
    id: "who-growth-reference-2007",
    organization: "World Health Organization (WHO)",
    title: "Growth reference data for 5–19 years",
    scope: "Khung tham chiếu tăng trưởng WHO 2007 cho trẻ và vị thành niên 61–228 tháng.",
    url: "https://www.who.int/tools/growth-reference-data-for-5to19-years",
    referenceYear: 2007,
    jurisdiction: "global",
    reviewedAt: "2026-09-08",
    reviewDueAt: "2027-09-08",
  },
  whoBmiForAge: {
    id: "who-bmi-for-age-5-19",
    organization: "World Health Organization (WHO)",
    title: "BMI-for-age (5–19 years)",
    scope: "Bảng LMS/z-score theo tháng và giới tính; các ngưỡng gầy, thừa cân, béo phì.",
    url: "https://www.who.int/toolkits/growth-reference-data-for-5to19-years/indicators/bmi-for-age",
    referenceYear: 2007,
    jurisdiction: "global",
    reviewedAt: "2026-09-08",
    reviewDueAt: "2027-09-08",
  },
  whoZScoreComputation: {
    id: "who-growth-zscore-computation",
    organization: "World Health Organization (WHO)",
    title: "Computation of centiles and z-scores for height-for-age, weight-for-age and BMI-for-age",
    scope: "Công thức LMS và quy tắc mở rộng tuyến tính ở ngoài ±3 SD.",
    url: "https://cdn.who.int/media/docs/default-source/child-growth/growth-reference-5-19-years/computation.pdf",
    referenceYear: 2007,
    jurisdiction: "global",
    reviewedAt: "2026-09-08",
    reviewDueAt: "2027-09-08",
  },
  whoAdolescentHealth: {
    id: "who-adolescent-health",
    organization: "World Health Organization (WHO)",
    title: "Adolescent health",
    scope: "Khung bao quát sức khỏe vị thành niên 10–19 tuổi: phát triển thể chất/tâm lý-xã hội, dinh dưỡng, hoạt động thể lực, chất gây nghiện, sức khỏe sinh sản, môi trường an toàn và tiếp cận dịch vụ.",
    url: "https://www.who.int/health-topics/adolescent-health/",
    jurisdiction: "global",
    reviewedAt: "2026-09-08",
    reviewDueAt: "2027-03-08",
  },
  whoGamaIndicators: {
    id: "who-gama-adolescent-indicators-2024",
    organization: "World Health Organization (WHO) / GAMA",
    title: "The adolescent health indicators recommended by the Global Action for Measurement of Adolescent health",
    scope: "Bộ 47 chỉ số khuyến nghị để tránh bỏ sót các miền sức khỏe vị thành niên khi thiết kế hệ thống theo dõi.",
    url: "https://www.who.int/publications/i/item/9789240092198/",
    referenceYear: 2024,
    jurisdiction: "global",
    reviewedAt: "2026-09-08",
    reviewDueAt: "2027-03-08",
  },
  whoAdolescentMentalHealth: {
    id: "who-adolescent-mental-health-2025",
    organization: "World Health Organization (WHO)",
    title: "Mental health of adolescents",
    scope: "Các yếu tố nguy cơ/bảo vệ và tầm quan trọng của hỗ trợ sức khỏe tâm thần ở trẻ vị thành niên.",
    url: "https://www.who.int/vietnam/news/fact-sheets/detail/adolescent-mental-health",
    referenceYear: 2025,
    jurisdiction: "global",
    reviewedAt: "2026-09-08",
    reviewDueAt: "2027-03-08",
  },
  aapBrightFuturesPeriodicity: {
    id: "aap-bright-futures-periodicity-2025",
    organization: "American Academy of Pediatrics (AAP) / Bright Futures",
    title: "Recommendations for Preventive Pediatric Health Care (Periodicity Schedule)",
    scope: "Nguồn tham chiếu quốc tế để kiểm tra cấu trúc khám/sàng lọc dự phòng theo tuổi; không được dùng làm lịch mặc định cho Việt Nam nếu chưa map sang cấu hình quốc gia.",
    url: "https://www.aap.org/periodicityschedule",
    referenceYear: 2025,
    jurisdiction: "united-states",
    reviewedAt: "2026-09-08",
    reviewDueAt: "2027-03-08",
  },
  vietnamSchoolHealth: {
    id: "vietnam-school-health-monitoring",
    organization: "Bộ Y tế Việt Nam",
    title: "Theo dõi sức khỏe học sinh",
    scope: "Khung y tế học đường gồm theo dõi chiều cao/cân nặng, huyết áp, nhịp tim, thị lực, răng miệng, bất thường và hướng dẫn tự chăm sóc; dùng làm nguồn cấu hình Việt Nam sau khi đối chiếu văn bản còn hiệu lực.",
    url: "https://moh.gov.vn/documents/20182/212437/81711.%20Phu%20luc%20TTLT%2013.2016_PL17_18_19_20.pdf/d85a3ebd-68e1-4547-b5c9-a602a39a2847",
    jurisdiction: "vietnam",
    reviewedAt: "2026-09-08",
    reviewDueAt: "2027-03-08",
  },
  vietnamExpandedImmunization2026: {
    id: "vietnam-expanded-immunization-2026-2028",
    organization: "Bộ Y tế Việt Nam",
    title: "Kế hoạch tiêm chủng mở rộng 2026–2028",
    scope: "Nguồn định hướng cấu hình Việt Nam cho tiêm chủng mở rộng, bao gồm lộ trình bổ sung HPV/phế cầu; lịch cá nhân vẫn phải dựa vào hướng dẫn/chương trình chính thức và hồ sơ từng trẻ.",
    url: "https://moh.gov.vn/en_US/hoat-dong-cua-lanh-dao-bo/-/asset_publisher/k206Q9qkZOqn/content/ke-hoach-tiem-vaccine-phe-cau-va-hpv-trong-tiem-chung-mo-rong",
    referenceYear: 2026,
    jurisdiction: "vietnam",
    reviewedAt: "2026-09-08",
    reviewDueAt: "2027-01-08",
  },
} as const satisfies Record<string, HealthEvidenceSource>;

export const WHO_BMI_REFERENCE_NOTE = "WHO Reference 2007 · BMI-for-age 5–19 years";
