export const HEALTH_MANAGEMENT_CONTRACT = {
  schemaVersion: 1,
  application: "health-care",
  canonicalApplication: "health-care",
  displayName: "Sức khỏe Y tế",
  contractVersion: 3,
  controlProtocol: "application-management-health-control-v1",
  transport: "https-worker",
  hosting: {
    primaryTarget: "cloudflare-workers",
    legacyTarget: "chatgpt-sites",
    originBound: true,
  },
  auth: {
    ticketVersion: "v1",
    issuer: "application-management",
    audience: "health-care-control",
    app: "health-care",
    ttlSeconds: 300,
    webLaunchTtlSeconds: 60,
    secretEnv: "HEALTH_CONTROL_SERVICE_SECRET",
  },
  endpoints: {
    contract: "/api/control/contract",
    status: "/api/control/status",
    devices: "/api/control/devices",
    deviceCommands: "/api/control/device-commands",
    sessions: "/api/control/sessions",
    policy: "/api/control/policy",
    automation: "/api/control/automation",
    contentReview: "/api/control/health-content",
    audit: "/api/control/audit",
    webLaunchTarget: "/suc-khoe-tre",
  },
  deviceRegistry: {
    owner: "Health_Care",
    namespace: "SK-",
    classes: ["desktop", "tablet", "phone"],
  },
  capabilities: [
    "device-access",
    "device-idempotent-commands",
    "device-auto-approval",
    "device-auto-block-pending",
    "control-web-launch",
    "device-edit-permission",
    "device-calendar-permission",
    "session-revocation",
    "access-policy",
    "content-review",
    "control-audit",
  ],
  boundary: {
    independentRuntime: true,
    adminRuntimeEmbedded: false,
    healthDataInControlPlane: false,
    profileDataInControlPlane: false,
    sharedClientDatabase: false,
  },
} as const;

export type HealthManagementContract = typeof HEALTH_MANAGEMENT_CONTRACT;
